stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: harryai/hello-world:v1.0.0
      registry: https://jy8ap06d.mirror.aliyuncs.com
timeout: 60
