stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: harryai/test/hello-world:v1
      pushRemote: true
      registry: index.docker.io
timeout: 60
